### ISSUE TITLE
Consider adding OpenZiti for application-embedded security

### ISSUE THREAD

**Issue by dovholuknf** [anderspitman/obligator#4]
>Currently the API is only offered through unix sockets. This reduces the chance that it accidentally gets exposed, which is important because it's not authenticated in any way.

Would you be open to embedding zero trust directly into the project via OpenZiti? OpenZiti allows you to have secure connectivity to the server from anywhere, via a zero trust overlay.

If that sounds interesting, I'd be happy to contribute a patch and if you're into it, demo it over on our YouTube channel too?

**Comment by anderspitman** [comment]
Hi @dovholuknf, unless such an embedding is based on an open protocol (not just open code), I wouldn't really be interested. Is there such a protocol?
